version: '3.8'
services:
  web:
    build:
      context: ./nextjs/
      target: runner
    volumes:
      - ./nextjs/:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: 'onvu'
      MYSQL_USER: 'onvu'
      MYSQL_PASSWORD: 'P@ssw0rd'
      MYSQL_ROOT_PASSWORD: 'r00tP@ssw0rd'
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'onvu'
      MYSQL_USER: 'onvu'
      MYSQL_PASSWORD: 'P@ssw0rd'
      MYSQL_ROOT_PASSWORD: 'r00tP@ssw0rd'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
volumes:
  mariadb:
  nextjs: 